### ISSUE TITLE
scalameter as a transitive dependency

### ISSUE THREAD

**Issue by crispywalrus** [atnos-org/eff-cats#11]
So while running benchmarks is a good thing overall leaving scalameter as a runtime dependency with it's transitive dependencies isn't quite so good. Scalameter depends on jackson, scalachart, commons-math and on and on. Yes, I can exclude scalameter my dependencies but I really shouldn't have to. Perhaps a slight refactoring to put the benchmarks in their own package is in order.

**Comment by etorreborre** [comment]
Thanks I didn't realise that. I will remove this dependency from the production code in the next release.

**Comment by etorreborre** [comment]
Removed on master. Will be published in `1.7.1` soon.
