### ISSUE TITLE
Errors interpreting stacks in Eff 2.0 RC7 in ammonite repl

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff-cats#15]
I started out seeing strange order-dependence in a non open source codebase using a `Fx.fx6` stack, as others had reported on gitter, for code that IIRC worked fine on 1.7.x. Got it to compile and run by interpreting in this order: Option, State, State, Reader, Writer, Xor.

So I tried to simplify the problem down in an ammonite repl, but saw alot of more basic errors for things that I thought should work: https://gist.github.com/benhutchison/720fcea4e03692bef383b3c05694981a

**Comment by etorreborre** [comment]
Did you try to load Miles's plugin as well?
```scala
addCompilerPlugin("com.milessabin" % "si2712fix-plugin_2.11.8" % "1.2.0")
```

**Comment by benhutchison** [comment]
Yep, that was it. Once I added it I wasn't able to come up with anything that seemed wrong.
