### ISSUE TITLE
Provide syntax to lift plain values into Eff?

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff-cats#17]
I have this mixed-in thru a package object:
```
  implicit class Id[A](val a: A) {
    def pureEff[E]: Eff[E, A] = EffMonad[E].pure(a)
  }
```

I find it regularly useful, allows type `A` to be inferred. I chose `pureEff` rather than `pure` because of name collision.

**Comment by etorreborre** [comment]
This is almost available with standard cats
```
1.pure[Eff[R, ?]]
```

I agree that `1.pureEff[R]` would be syntactically more pleasing, I will add this.
