### ISSUE TITLE
Add interpret.augment

### ISSUE THREAD

**Issue by edmundnoble** [atnos-org/eff-cats#20]
Add a way to use a `F ~> Union2[Fx.fx2[F, G], ?]` to use the info contained in `F`'s structure to add a `G` effect to an effect stack already containing an `F`. I'm thinking `interpret.augment` but that's just an idea.

**Comment by etorreborre** [comment]
I think you can use `into` for this scenario
```scala
import org.atnos.eff.syntax.all._

type R = Fx.fx1[F]
type S = Fx.fx2[F, G]

val action1: Eff[R, Int] = ...

def action2[U](implicit g: MemberIn[G, U]): Eff[U, String] = ???

val action2: Eff[S, String] = for {
  a <- action1.into[S]
  b <- action2[S]
} yield a.toString + b
```

With `into` you can "inject" the effects of a stack (`R`) into a larger stack (`S`).

**Comment by edmundnoble** [comment]
I believe what I was looking for was closer to a combo of `into` and `interpret.translate`:
```
  def log[I[_], O[_], U[_], A](eff: Eff[I, A])
  (implicit ev: Member.Aux[StorageAction, I, U], ev2: Member.Aux[Writer[Vector[String], ?], O, I]): Eff[O, A] = {
    interpret.translate[O, O, StorageAction, A](eff.into[O])(new interpret.Translate[StorageAction, O] {
      override def apply[X](kv: StorageAction[X]): Eff[O, X] = {
        val keys = kv match {
          case StorageAction.Get(k) => Vector.empty[String] :+ k
          case StorageAction.Update(k, _) => Vector.empty[String] :+ k
          case StorageAction.Remove(_) => Vector.empty[String]
        }
         for {
           _ <- writer.tell[O, Vector[String]](keys)
           r <- kv.send[O]
         } yield r
      }
    })
  }
```

Either way, looks like it's solved. I'll close.

**Comment by etorreborre** [comment]
I have added in `2.0.0-RC19-20161101104422-0b414c3` some support for this kind of use case. See [here](https://github.com/atnos-org/eff-cats/blob/master/shared/src/main/scala/org/atnos/eff/Interpret.scala#L357) and [there](https://github.com/atnos-org/eff-cats/blob/master/jvm/src/test/scala/org/atnos/eff/EffSpec.scala#L262).
