### ISSUE TITLE
Error effect interpreter with parallel error accumulation

### ISSUE THREAD

**Issue by edmundnoble** [atnos-org/eff-cats#21]
There should be an error effect interpreter that allows one to use a `Semigroup` to accumulate errors during `traverse` calls, instead of failing immediately (a là `cats.data.Validated`).

**Comment by etorreborre** [comment]
Are you looking for the [Validate effect](http://atnos-org.github.io/eff-cats/org.atnos.site.OutOfTheBox.html#validate)?

**Comment by edmundnoble** [comment]
The `Validate` effect appears to keep going as errors are emitted. I'm talking about a different interpretation of the `Error`effect, which replaces its applicative action only for more descriptive error info.

I have an implementation of this effect with `cats.data.Validated` used as the underlying data type, you can see it here: http://pastebin.com/n3rs1JFw.
