### ISSUE TITLE
XorT example

### ISSUE THREAD

**Issue by pavlosgi** [atnos-org/eff-cats#7]
I am trying to do
```
XorT.pure(eff)
```
 where 
```
eff: Eff[SomeEffect, Validated[E, A]]
```
and I get the following errors:

```
[error]  both value listInstance in trait ListInstances of type => cats.Traverse[List] with cats.MonadCombine[List] with cats.CoflatMap[List]
[error]  and value optionInstance in trait OptionInstances of type => cats.Traverse[Option] with cats.MonadCombine[Option] with cats.CoflatMap[Option] with cats.Alternative[Option]
[error]  match expected type cats.Applicative[F]
[error]     XorT.pure(s)
```

This is very weird since my Eff type has nothing to do with Option nor List. Weirdly if I do this:

```
XorT.pure(s)(optionInstance)
```
it compiles

**Comment by etorreborre** [comment]
Can you post a full gist with all your imports?

The other question is: what are you trying to achieve by mixing `Eff` and monad transformers?

**Comment by pavlosgi** [comment]
I'd like to use for comprehension with Eff and Xor

**Comment by pavlosgi** [comment]
I created this [Gist](https://gist.github.com/pavlosgi/c33e26460e594dd6095340b3532a1fdc) where I am trying to do sequence to a List of effects and get the same error 

```
[error]  both value function0Instance in trait Function0Instances of type => cats.Bimonad[Function0]
[error]  and value optionInstance in trait OptionInstances of type => cats.Traverse[Option] with cats.MonadCombine[Option] with cats.CoflatMap[Option] with cats.Alternative[Option]
[error]  match expected type cats.Applicative[G]
[error]   val efs = list.sequence
```

**Comment by pavlosgi** [comment]
I also created this [Gist](https://gist.github.com/pavlosgi/6cf3682beb3a09d1a2907ce8a86e48a8) where I am trying to use XorT with Eff

**Comment by etorreborre** [comment]
This compiled for me with
```scala
import cats.std.list._
val efs = list.sequenceU
```

**Comment by pavlosgi** [comment]
Should have tried that, wasn't aware that cats also provides sequenceU like scalaz does. Yep that works for me as well and also ```list.traverseU(identity)```. Any ideas on XorT ? Thanks a lot btw

**Comment by etorreborre** [comment]
If you write `XorT.pure(efs)` just after `val efs = list.sequenceU` everything compiles ok.

**Comment by etorreborre** [comment]
I am closing this for now. Please feel free to discuss again on [gitter](https://gitter.im/atnos-org/eff-cats).
